In [1]:
import pandas  as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 

In [3]:
df=pd.read_csv(r"E:\DataScience-data\bbc_news_mixed.csv")

In [4]:
df.shape

(2225, 2)

In [5]:
df.head()

text     label
0  Cairn shares slump on oil setback\n\nShares in...  business
1  Egypt to sell off state-owned bank\n\nThe Egyp...  business
2  Cairn shares up on new oil find\n\nShares in C...  business
3  Low-cost airlines hit Eurotunnel\n\nChannel Tu...  business
4  Parmalat to return to stockmarket\n\nParmalat,...  business

In [6]:
df['label'].value_counts()

sport            511
business         510
politics         417
tech             401
entertainment    386
Name: label, dtype: int64

In [7]:
from sklearn.preprocessing import LabelEncoder
l1=LabelEncoder()
df['label']=l1.fit_transform(df['label'])

In [8]:
df.head()

text  label
0  Cairn shares slump on oil setback\n\nShares in...      0
1  Egypt to sell off state-owned bank\n\nThe Egyp...      0
2  Cairn shares up on new oil find\n\nShares in C...      0
3  Low-cost airlines hit Eurotunnel\n\nChannel Tu...      0
4  Parmalat to return to stockmarket\n\nParmalat,...      0

In [9]:
df['label'].value_counts()

3    511
0    510
2    417
4    401
1    386
Name: label, dtype: int64

In [11]:
for i in df.text[:2]:
    print(i)

Cairn shares slump on oil setback

Shares in Cairn Energy, a UK oil firm, have closed down 18% after a disappointing drilling update and a warning over possible tax demands.

The company said tests had shown no significant finds in one of its Indian oil fields, but was upbeat about the potential of other areas. It also said the Indian government had told it to pay a production tax, for which Cairn argues it is not liable. Cairn's shares have jumped by almost 400% this year. Investors had piled into Cairn after the company announced significant oil finds in India this year. Chief executive Bill Gammell said on Friday he was "disappointed" with exploration in the so-called N-C extension area in Rajasthan. Investors had held high hopes of major oil finds in this area. But Cairn said estimates had been revised in what was a "significant downgrade of the initial expectation".

Cairn also said that the government believed the company was liable to pay taxes under its production-sharing contr

In [127]:
from sklearn.feature_extraction.text import CountVectorizer
conv=CountVectorizer(stop_words='english')

In [128]:
sample_data=['This is smaple documents', 'This is second documents','This is my documents']

In [129]:
#c=CountVectorizer()

In [130]:
##xsample=c.fit_transform(sample_data)

In [131]:
#c.get_feature_names()

In [132]:
#print(xsample.toarray())

In [133]:
bow=conv.fit_transform(df.text)

In [134]:
bow.shape

(2225, 29126)

In [135]:
len(conv.vocabulary_)

29126

In [136]:
bow_df=pd.DataFrame.sparse.from_spmatrix(bow, columns=conv.get_feature_names(),
                                        index=df.index)

In [137]:
type(bow_df)

pandas.core.frame.DataFrame

In [138]:
bow_df.head()

00  000  0001  000bn  000m  000s  000th  001  001and  001st  ...  zooms  \
0   0    3     0      0     0     0      0    0       0      0  ...      0   
1   0    0     0      0     0     0      0    0       0      0  ...      0   
2   0    0     0      0     0     0      0    0       0      0  ...      0   
3   0    0     0      0     0     0      0    0       0      0  ...      0   
4   0    0     0      0     0     0      0    0       0      0  ...      0   

   zooropa  zornotza  zorro  zubair  zuluaga  zurich  zutons  zvonareva  \
0        0         0      0       0        0       0       0          0   
1        0         0      0       0        0       0       0          0   
2        0         0      0       0        0       0       0          0   
3        0         0      0       0        0       0       0          0   
4        0         0      0       0        0       0       0          0   

   zvyagintsev  
0            0  
1            0  
2            0  
3            0  
4            0  

[5 rows x 29126 columns]

In [139]:
bow_df.iloc[:20,5000:5050]

callaghan  callam  called  calleri  callers  calling  callow  calls  calm  \
0           0       0       1        0        0        0       0      0     0   
1           0       0       0        0        0        0       0      0     0   
2           0       0       0        0        0        0       0      0     0   
3           0       0       0        0        0        0       0      0     0   
4           0       0       0        0        0        0       0      0     0   
5           0       0       0        0        0        0       0      0     0   
6           0       0       0        0        0        0       0      0     0   
7           0       0       0        0        0        0       0      0     0   
8           0       0       0        0        0        0       0      0     0   
9           0       0       0        0        0        0       0      0     0   
10          0       0       0        0        0        0       0      0     0   
11          0       0       0        0        0        0       0      0     0   
12          0       0       0        0        0        0       0      0     0   
13          0       0       0        0        0        0       0      0     0   
14          0       0       0        0        0        0       0      0     0   
15          0       0       0        0        0        0       0      0     0   
16          0       0       0        0        0        0       0      0     0   
17          0       0       0        0        0        0       0      0     0   
18          0       0       0        0        0        0       0      1     0   
19          0       0       0        0        0        0       0      0     0   

    calmed  ...  camp  campaiging  campaign  campaigned  campaigner  \
0        0  ...     0           0         0           0           0   
1        0  ...     0           0         0           0           0   
2        0  ...     0           0         0           0           0   
3        0  ...     0           0         0           0           0   
4        0  ...     0           0         0           0           0   
5        0  ...     0           0         0           0           0   
6        0  ...     0           0         0           0           0   
7        0  ...     0           0         0           0           0   
8        0  ...     0           0         0           0           0   
9        0  ...     0           0         0           0           0   
10       0  ...     0           0         0           0           0   
11       0  ...     0           0         0           0           0   
12       0  ...     0           0         0           0           0   
13       0  ...     0           0         0           0           0   
14       0  ...     0           0         0           0           0   
15       0  ...     0           0         0           0           0   
16       0  ...     0           0         0           0           0   
17       0  ...     0           0         0           0           0   
18       0  ...     0           0         0           0           0   
19       0  ...     0           0         0           0           0   

    campaigners  campaigning  campaigns  campbell  camped  
0             0            0          0         0       0  
1             0            0          0         0       0  
2             0            0          0         0       0  
3             0            0          0         0       0  
4             0            0          0         0       0  
5             0            0          0         0       0  
6             0            0          0         0       0  
7             0            0          0         0       0  
8             0            0          0         0       0  
9             0            0          0         0       0  
10            0            0          0         0       0  
11            0            0          0         0       0  
12            0            0  

In [140]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(bow,df.label,train_size=0.8)

In [141]:
print(xtrain[0].shape)
print(xtest.shape)
print(ytrain.shape)
print(ytest.shape)

(1, 29126)
(445, 29126)
(1780,)
(445,)


In [142]:
from sklearn.neural_network import MLPClassifier
algo=MLPClassifier()
algo.fit(xtrain,ytrain)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(100,), learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=200,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=None, shuffle=True, solver='adam',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)

In [143]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [144]:
ypred=algo.predict(xtest)

In [145]:
accuracy_score(ytest,ypred)

0.9820224719101124

In [146]:
confusion_matrix(ytest,ypred)

array([[ 90,   0,   0,   0,   0],
       [  1,  76,   1,   0,   0],
       [  0,   1,  87,   0,   0],
       [  0,   0,   0, 102,   0],
       [  2,   2,   0,   1,  82]], dtype=int64)

In [147]:
newdata=["""The CSK squad have been in quarantine over the last week until it emerged yesterday that they would continue to remain so after a few members from the team had tested positive for COVID-19.

It is a significant blow for CSK, the three-time IPL champions. Raina is the team's leading run-getter, aggregating 4527 runs from 164 IPL games for the franchise. The No.3 batsman featured in 158 consecutive games for CSK (IPL + CPL) before missing his first game in the 2018 season with a calf injury.

Raina is also the second-highest scorer in IPL history with 5368 runs, only behind Virat Kohli's tally of 5412, and has taken the most catches (102) in the tournament history."""]

In [148]:
ndata=conv.transform(newdata)

In [149]:
ndata.shape

(1, 29126)

In [150]:
algo.predict(ndata)

array([3])

In [154]:
mydata=["""Coca-Cola is offering voluntary buyouts to about 4,000 people to reduce the number of layoffs it says will take place as it streamlines operations.

Coca-Cola is reducing the number of its individual business segments from 17 to nine, which it said Friday will result in “voluntary and involuntary” staff cuts.

The streamlining is taking place during a rough stretch for Coca-Cola and almost all companies that cater to social events.

Half of Coca-Cola’s sales come from stadiums, movie theaters and other places where people gather in large numbers — venues that have been closed during the coronavirus pandemic. Revenue tumbled 28% in the Atlanta company's most recent quarter."""]

In [155]:
nndata=conv.transform(mydata)

In [156]:
algo.predict(nndata)

array([0])